# Generated by Django 5.2.17 on 2026-08-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('grupo', models.CharField(choices=[('clinico', 'Sistemas clínicos/assistenciais'), ('rede', 'Infraestrutura de rede'), ('suporte', 'Suporte ao usuário'), ('equipamento', 'Equipamentos e periféricos'), ('acesso', 'Acessos e permissões')], max_length=20)),
                ('peso_categoria', models.PositiveSmallIntegerField(help_text='Criticidade intrínseca do serviço, de 1 a 5')),
                ('sla_horas', models.DecimalField(decimal_places=2, help_text='Tempo esperado de atendimento, em horas', max_digits=6)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['grupo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('chave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Parâmetro do sistema',
                'verbose_name_plural': 'Parâmetros do sistema',
            },
        ),
        migrations.CreateModel(
            name='RegraRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_desvio', models.CharField(max_length=100)),
                ('condicao', models.CharField(help_text='Descrição da condição que dispara esta regra, referenciando chaves de ParametroSistema', max_length=255)),
                ('acao_sugerida', models.TextField()),
            ],
            options={
                'verbose_name': 'Regra de recomendação',
                'verbose_name_plural': 'Regras de recomendação',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('peso_setor', models.PositiveSmallIntegerField(help_text='Criticidade operacional do setor, de 1 a 5')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_gerada', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categoria')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.regrarecomendacao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.setor')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-data_gerada'],
            },
        ),
        migrations.CreateModel(
            name='ItemConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em manutenção'), ('baixado', 'Baixado')], default='ativo', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.setor')),
            ],
            options={
                'verbose_name': 'Item de configuração',
                'verbose_name_plural': 'Itens de configuração (CMDB)',
                'ordering': ['patrimonio'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('prioridade_calculada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('categoria_final', models.ForeignKey(blank=True, help_text='Categoria confirmada pelo técnico — usada no cálculo de SLA e prioridade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_como_final', to='tickets.categoria')),
                ('categoria_ia', models.ForeignKey(blank=True, help_text='Categoria determinada pelo modelo de IA a partir da descrição', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_como_classificada_ia', to='tickets.categoria')),
                ('categoria_sugerida', models.ForeignKey(help_text='Categoria selecionada pelo usuário solicitante ao abrir o ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_como_sugerida', to='tickets.categoria')),
                ('item_configuracao', models.ForeignKey(blank=True, help_text='Equipamento do CMDB relacionado ao ticket, quando aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.itemconfiguracao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.setor')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-prioridade_calculada', 'data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_real', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tempo_esperado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desvio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Histórico de SLA',
                'verbose_name_plural': 'Históricos de SLA',
            },
        ),
        migrations.CreateModel(
            name='ExcecaoPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_override', models.PositiveSmallIntegerField(help_text='Peso de prioridade que substitui o cálculo padrão (peso_categoria × peso_setor) para esta combinação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categoria')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.setor')),
            ],
            options={
                'verbose_name': 'Exceção de prioridade',
                'verbose_name_plural': 'Exceções de prioridade',
                'unique_together': {('categoria', 'setor')},
            },
        ),
    ]
