# Generated by Django 5.2.17 on 2026-08-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_substituir_catalogo_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante_nome',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_ramal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_sala',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
