# Generated by Django 5.2.17 on 2026-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_solicitante_nome_ticket_solicitante_ramal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='requer_patrimonio',
            field=models.BooleanField(default=False, help_text='Se marcado, a abertura do chamado exige o número de patrimônio do equipamento'),
        ),
    ]
