# Generated by Django 5.2.17 on 2026-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_marcar_categorias_com_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP do computador usado para abrir o chamado, capturado automaticamente', null=True),
        ),
    ]
