# Generated by Django 5.2.17 on 2026-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_solicitante_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconfiguracao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='itemconfiguracao',
            name='categoria',
            field=models.CharField(choices=[('computador', 'Computador'), ('monitor', 'Monitor'), ('impressora', 'Impressora'), ('scanner', 'Scanner'), ('telefone_voip', 'Telefone VoIP'), ('mouse', 'Mouse'), ('teclado', 'Teclado'), ('webcam', 'Webcam'), ('outro', 'Outro')], default='outro', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemconfiguracao',
            name='marca',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemconfiguracao',
            name='modelo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
