# Generated by Django 5.2.17 on 2026-08-12 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_itemconfiguracao_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='gestor',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pelo setor, autorizado a editar os equipamentos dele', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_geridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
