# Generated by Django 5.2.17 on 2026-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_comentarioticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='impacto',
            field=models.CharField(choices=[('apenas_eu', 'Apenas eu'), ('meu_departamento', 'Meu departamento'), ('empresa_inteira', 'Empresa inteira')], default='apenas_eu', help_text='Quem ou o que está sendo impactado pelo problema', max_length=20),
        ),
    ]
