# Generated by Django 5.2.17 on 2026-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_impacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movimentacao_confirmada',
            field=models.BooleanField(default=False, help_text='Marcado quando o técnico registra uma movimentação de equipamento ou confirma explicitamente que não houve nenhuma — exigido para fechar o chamado'),
        ),
    ]
