# Generated by Django 5.2.17 on 2026-08-12 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_movimentacao_confirmada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_movimentacao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipamento_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_como_entrada', to='tickets.itemconfiguracao')),
                ('equipamento_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_como_saida', to='tickets.itemconfiguracao')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_equipamento', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Movimentação de equipamento',
                'verbose_name_plural': 'Movimentações de equipamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
