# Generated by Django 5.2.17 on 2026-08-12 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_renomear_patrimonios_para_6_digitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconfiguracao',
            name='patrimonio',
            field=models.CharField(help_text='6 dígitos numéricos, sem letras (ex: 000123)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='O patrimônio deve ter exatamente 6 dígitos numéricos, sem letras.', regex='^\\d{6}$')]),
        ),
    ]
