# Generated by Django 5.2.17 on 2026-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_itemconfiguracao_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioticket',
            name='tipo',
            field=models.CharField(choices=[('nota_interna', 'Nota interna'), ('resposta_usuario', 'Resposta ao usuário'), ('desfecho', 'Desfecho/solução final')], default='nota_interna', max_length=20),
        ),
    ]
