# Generated by Django 5.2.17 on 2026-08-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_comentarioticket_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, help_text='Breve resumo exibido na listagem (opcional)', max_length=300)),
                ('conteudo', models.TextField(help_text='Corpo do artigo ou tutorial')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria de chamado relacionada, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='tickets.categoria')),
            ],
            options={
                'verbose_name': 'Artigo da base de conhecimento',
                'verbose_name_plural': 'Artigos da base de conhecimento',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
