# Generated by Django 5.2.17 on 2026-08-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_migrar_parametro_setor_ti_para_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='sigla',
        ),
    ]
