# Generated by Django 5.2.17 on 2026-08-13 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_setor_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(blank=True, help_text='Usuário autenticado que abriu o chamado, usado para a tela "Meus chamados"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_abertos', to=settings.AUTH_USER_MODEL),
        ),
    ]
