# Generated by Django 5.2.17 on 2026-08-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_backfill_ticket_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(choices=[('impressora', 'Impressora'), ('computador', 'Computador e periféricos'), ('rede', 'Rede e telefonia'), ('acesso', 'Acessos e permissões'), ('clinico', 'Sistemas clínicos/assistenciais'), ('suporte', 'Software e suporte geral')], max_length=20),
        ),
    ]
