# Generated by Django 5.2.17 on 2026-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_reclassificar_categorias_por_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoequipamento',
            name='aplicada',
            field=models.BooleanField(default=False, help_text='Marcado quando a movimentação é efetivamente aplicada ao CMDB — isso só acontece quando o chamado é fechado, não no momento do registro'),
        ),
    ]
