# Generated by Django 5.2.17 on 2026-08-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_marcar_movimentacoes_existentes_como_aplicadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconfiguracao',
            name='status',
            field=models.CharField(choices=[('ativo', 'Disponível'), ('manutencao', 'Em triagem'), ('baixado', 'Baixado')], default='ativo', max_length=20),
        ),
    ]
