# Generated by Django 5.2.17 on 2026-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_item_status_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconfiguracao',
            name='data_validade_garantia',
            field=models.DateField(blank=True, help_text='Data em que a garantia do equipamento expira, se houver', null=True),
        ),
    ]
