# Generated by Django 5.2.17 on 2026-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição')], default='incidente', help_text='Incidente: algo quebrou e precisa ser restaurado. Requisição: um pedido padrão, sem urgência de falha.', max_length=20),
        ),
    ]
