# Generated by Django 5.2.17 on 2026-08-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_seed_fatores_prioridade_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição')], max_length=20, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de chamado',
                'verbose_name_plural': 'Contadores de chamado',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo_numero',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo_tipo',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição')], default='incidente', max_length=20),
            preserve_default=False,
        ),
    ]
