# Generated by Django 5.2.17 on 2026-08-28 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_backfill_codigo_chamados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('codigo_tipo', 'codigo_numero'), name='ticket_codigo_unico'),
        ),
    ]
