# Generated by Django 5.2.17 on 2026-08-29 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_ticket_ticket_codigo_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, help_text='Técnico responsável pelo atendimento deste chamado', limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
