# Generated by Django 5.2.17 on 2026-08-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_alter_ticket_tecnico_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome curto, mostrado no botão de inserir', max_length=100)),
                ('texto', models.TextField(help_text='Texto inserido no comentário ao clicar')),
                ('tipo_padrao', models.CharField(blank=True, choices=[('nota_interna', 'Nota interna'), ('resposta_usuario', 'Resposta ao usuário'), ('desfecho', 'Desfecho/solução final')], help_text='Se definido, já marca esse tipo de comentário ao inserir o template', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Resposta rápida',
                'verbose_name_plural': 'Respostas rápidas',
                'ordering': ['titulo'],
            },
        ),
    ]
