# Generated by Django 5.2.17 on 2026-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_seed_respostas_rapidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostarapida',
            options={'ordering': ['grupo', 'titulo'], 'verbose_name': 'Resposta rápida', 'verbose_name_plural': 'Respostas rápidas'},
        ),
        migrations.AddField(
            model_name='respostarapida',
            name='grupo',
            field=models.CharField(blank=True, choices=[('impressora', 'Impressora'), ('computador', 'Computador e periféricos'), ('rede', 'Rede e telefonia'), ('acesso', 'Acessos e permissões'), ('clinico', 'Sistemas clínicos/assistenciais'), ('suporte', 'Software e suporte geral')], help_text='Agrupa esse modelo na listagem — mesma classificação usada nas categorias de chamado', max_length=20, null=True),
        ),
    ]
