# Generated by Django 5.2.17 on 2026-08-29 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_seed_grupo_respostas_rapidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaRapidaEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes', to='tickets.respostarapida')),
            ],
            options={
                'verbose_name': 'Edição de resposta rápida',
                'verbose_name_plural': 'Edições de resposta rápida',
                'ordering': ['-criado_em'],
            },
        ),
    ]
