# Generated by Django 5.2.17 on 2026-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_respostarapidaedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconfiguracao',
            name='data_inicio_resguardo',
            field=models.DateField(blank=True, help_text='Data de desligamento do funcionário / início do resguardo', null=True),
        ),
        migrations.AddField(
            model_name='itemconfiguracao',
            name='nivel_cargo_desligado',
            field=models.CharField(blank=True, choices=[('lideranca', 'Gestor ou diretor'), ('colaborador', 'Outro cargo')], help_text='Cargo do funcionário desligado — define o prazo de resguardo (30 dias para liderança, 15 dias para os demais cargos)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemconfiguracao',
            name='status',
            field=models.CharField(choices=[('ativo', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Em triagem'), ('em_resguardo', 'Em resguardo'), ('resguardo_liberado', 'Resguardo encerrado — liberado para formatação'), ('baixado', 'Baixado')], default='ativo', max_length=20),
        ),
    ]
