# Generated by Django 5.2.17 on 2026-08-30 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_itemconfiguracao_data_inicio_resguardo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nivel_atendimento',
            field=models.CharField(choices=[('n1', 'N1'), ('n2', 'N2'), ('n3', 'N3')], default='n1', help_text='Nível de atendimento de origem dessa categoria — a maioria fica em N1; cure aqui as que exigem um especialista (N2/N3)', max_length=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nivel_atual',
            field=models.CharField(choices=[('n1', 'N1'), ('n2', 'N2'), ('n3', 'N3')], default='n1', help_text='Nível de atendimento atual do chamado — muda só por escalonamento explícito', max_length=5),
        ),
        migrations.CreateModel(
            name='EscalonamentoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_anterior', models.CharField(choices=[('n1', 'N1'), ('n2', 'N2'), ('n3', 'N3')], max_length=5)),
                ('nivel_novo', models.CharField(choices=[('n1', 'N1'), ('n2', 'N2'), ('n3', 'N3')], max_length=5)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalonamentos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Escalonamento de chamado',
                'verbose_name_plural': 'Escalonamentos de chamado',
                'ordering': ['-criado_em'],
            },
        ),
    ]
