# Generated by Django 5.2.17 on 2026-08-30 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_categoria_nivel_atendimento_ticket_nivel_atual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('mudanca_status', 'Mudança de status'), ('novo_comentario', 'Novo comentário'), ('escalonamento', 'Escalonamento')], max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_atendimento', models.CharField(choices=[('n1', 'N1'), ('n2', 'N2'), ('n3', 'N3')], default='n1', help_text='Nível de atendimento desse técnico — usado pra notificá-lo quando um chamado é escalado pro nível dele', max_length=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de técnico',
                'verbose_name_plural': 'Perfis de técnico',
            },
        ),
    ]
