# Generated by Django 5.2.17 on 2026-08-31 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_backfill_perfil_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('mudanca_status', 'Mudança de status'), ('novo_comentario', 'Novo comentário'), ('escalonamento', 'Escalonamento'), ('transferencia', 'Transferência de chamado')], max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_transferencia', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Solicitação de transferência',
                'verbose_name_plural': 'Solicitações de transferência',
                'ordering': ['-criado_em'],
            },
        ),
    ]
