# Generated by Django 5.2.17 on 2026-09-01 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_alter_notificacao_tipo_solicitacaotransferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosla',
            name='tempo_pausado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de horas em que o chamado ficou com o SLA pausado — já descontado de tempo_real', max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('pausado', 'Pausado'), ('fechado', 'Fechado')], default='aberto', max_length=20),
        ),
        migrations.CreateModel(
            name='PausaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('aguardando_fornecedor', 'Aguardando fornecedor'), ('aguardando_peca', 'Aguardando peça/equipamento'), ('aguardando_usuario', 'Aguardando retorno do usuário'), ('aguardando_aprovacao', 'Aguardando aprovação/autorização'), ('outro', 'Outro motivo')], max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas_sla', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Pausa de SLA',
                'verbose_name_plural': 'Pausas de SLA',
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
