# Generated by Django 5.2.17 on 2026-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_codigorecuperacaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioticket',
            name='tipo',
            field=models.CharField(choices=[('nota_interna', 'Nota interna'), ('resposta_usuario', 'Resposta ao usuário'), ('resposta_solicitante', 'Resposta do solicitante'), ('desfecho', 'Desfecho/solução final')], default='nota_interna', max_length=20),
        ),
        migrations.AlterField(
            model_name='respostarapida',
            name='tipo_padrao',
            field=models.CharField(blank=True, choices=[('nota_interna', 'Nota interna'), ('resposta_usuario', 'Resposta ao usuário'), ('desfecho', 'Desfecho/solução final')], help_text="Se definido, já marca esse tipo de comentário ao inserir o template — não inclui 'Resposta do solicitante', que só o solicitante pode usar", max_length=20, null=True),
        ),
    ]
