# Generated by Django 5.2.17 on 2026-09-05 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_alter_comentarioticket_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconfiguracao',
            name='tecnico_responsavel_resguardo',
            field=models.ForeignKey(blank=True, help_text='Técnico que registrou o desligamento que colocou este equipamento em resguardo — avisado quando o prazo vence (ver services/equipamento.py: liberar_resguardos_vencidos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemconfiguracao',
            name='ticket_origem_resguardo',
            field=models.ForeignKey(blank=True, help_text='Chamado em que o retorno por desligamento foi registrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='movimentacaoequipamento',
            name='motivo_retorno',
            field=models.CharField(blank=True, choices=[('falta', 'Falta/defeito no equipamento'), ('desligamento', 'Desligamento de colaborador'), ('troca_comum', 'Troca comum')], help_text='Só quando há equipamento de saída (retornando pra TI)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoequipamento',
            name='nivel_cargo_desligado',
            field=models.CharField(blank=True, choices=[('lideranca', 'Gestor ou diretor'), ('colaborador', 'Outro cargo')], help_text='Só quando motivo_retorno=desligamento — define o prazo de resguardo aplicado automaticamente ao equipamento (ver services/equipamento.py: aplicar_movimentacoes_pendentes)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('mudanca_status', 'Mudança de status'), ('novo_comentario', 'Novo comentário'), ('escalonamento', 'Escalonamento'), ('transferencia', 'Transferência de chamado'), ('resguardo_liberado', 'Resguardo liberado')], max_length=20),
        ),
    ]
