# Generated by Django 5.2.17 on 2026-09-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0053_itemconfiguracao_tecnico_responsavel_resguardo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="confianca_ia",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Confiança do classificador na categoria_ia, de 0 a 1 — mostrada ao técnico na dupla checagem pra ele saber o quanto levar o palpite a sério",
                max_digits=5,
                null=True,
            ),
        ),
    ]
