# Generated by Django 5.2.17 on 2026-09-11 00:22
"""Habilita o formulário de criação de usuário só na categoria "Criação de
usuário (admissão)" (pk=52, estável desde 0002_seed_catalogo — só renomeada
em 0054_revisar_catalogo_categorias)."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CATEGORIA_ADMISSAO_PK = 52


def habilitar_criacao_usuario(apps, schema_editor):
    Categoria = apps.get_model("tickets", "Categoria")
    Categoria.objects.filter(pk=CATEGORIA_ADMISSAO_PK).update(habilita_criacao_usuario=True)


def reverter_criacao_usuario(apps, schema_editor):
    Categoria = apps.get_model("tickets", "Categoria")
    Categoria.objects.filter(pk=CATEGORIA_ADMISSAO_PK).update(habilita_criacao_usuario=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0056_revisar_catalogo_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='habilita_criacao_usuario',
            field=models.BooleanField(default=False, help_text='Se marcado, a tela do chamado mostra um formulário pra criar a conta do novo usuário ao resolver (ex: categoria de admissão)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario_criado',
            field=models.ForeignKey(blank=True, help_text='Usuário criado a partir deste chamado, se a categoria habilitar criação de usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_origem_criacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(habilitar_criacao_usuario, reverter_criacao_usuario),
    ]
