# Generated by Django 5.2.17 on 2026-09-15 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_seed_parametro_peso_setor_vital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackArtigoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.BooleanField(help_text='True = 👍 ajudou, False = 👎 não ajudou')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tickets.artigoconhecimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback de artigo da base de conhecimento',
                'verbose_name_plural': 'Feedbacks de artigos da base de conhecimento',
                'constraints': [models.UniqueConstraint(fields=('artigo', 'usuario'), name='feedback_artigo_por_usuario_unico')],
            },
        ),
    ]
